

# services:
#   client:
#     build: ./client
#     ports:
#       - "5173:5173"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#       - REACT_APP_API_URL=http://localhost:5000
#     volumes:
#       - ./client:/app
#       - /app/node_modules
#     stdin_open: true
#     tty: true

#   server:
#     build: ./server
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=development
#       - CLIENT_URL=http://localhost:3000
#     volumes:
#       - ./server:/app
#       - /app/node_modules
#     command: bun --watch index.ts



services:
  client:
    build: ./client
    ports:
      - "5174:5174"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:4343
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4343:4343"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/coffeemates_db
      - JWT_SECRET=coffeemates-dev-secret-2024
      - PORT=4343
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=coffeemates_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: